Added choice of version branch "direction"

diff --git a/bin/grelb b/bin/grelb
--- a/bin/grelb
+++ b/bin/grelb
@@ -63,35 +63,48 @@ while true; do
 done
 
 # Get the version direction
-versionDirection[0]="Serial (i.e. 1.1.1 -> 1.1.2)"
-versionDirection[1]="Child  (i.e. 1.1.1 -> 1.1.1.1)"
-versionDirection[3]="asdfsdfa.1)"
+NEXT_SERIAL_VERSION=`printSerialVersion $RELEASE_VERSION`
+NEXT_CHILD_VERSION=`printNextBranchVersionFor $RELEASE_VERSION`
 echo
 echo "   Please choose a \"direction\" for the new version"
 echo
-chooseFromNumberedChoices versionDirection[@]
-
-echo "Chose "$chooseFromNumberedChoices_returnValue
-echo
-exit 0
-
-#choice=""
-#while true; do
-#    echo
-#    if [ "$choice" != "" ]
-#    then
-#        read -p "   Choose a number [$choice] ? " value
-#    else
-#        read -p "   Choose a number ? " value
-#    fi
-#    if [ "$value" != "" ]
-#    then
-#        choice="$value"
-#        break
-#    else
-#        echo "   Please enter the number of the item to choose"
-#    fi
-#done
+echo "     1:  Serial (i.e. $RELEASE_VERSION -> $NEXT_SERIAL_VERSION)"
+echo "     2:  Child  (i.e. $RELEASE_VERSION -> $NEXT_CHILD_VERSION)"
+CHOICE=""
+while true; do
+    echo
+    if [ "$CHOICE" != "" ]
+    then
+        read -p "   Choose a number [$CHOICE] ? " value
+    else
+        read -p "   Choose a number ? " value
+    fi
+    if [ "$value" != "" ]
+    then
+        let numberChoice=0+$value
+        if [ $numberChoice -lt 1 ] || [ $numberChoice -gt 2 ]
+        then
+            echo "   $value is not a valid choice, please re-enter"
+        else
+            CHOICE="$numberChoice"
+            break
+        fi
+    else
+        echo "   Please enter the number of the item to choose"
+    fi
+done
+if [ "$CHOICE" == "1" ]
+then
+    BRANCH_VERSION=$NEXT_SERIAL_VERSION
+elif [ "$CHOICE" == "2" ]
+then
+    BRANCH_VERSION=$NEXT_CHILD_VERSION
+else
+        echo
+        echo "ERROR: Unexpected choice \"$CHOICE\""
+        echo
+        exit 1
+fi
 
 # Get the branch name
 BRANCH_NAME=""
@@ -112,10 +125,9 @@ while true; do
     fi
 done
 
-NEXT_BRANCH_VERSION=`printNextBranchVersionFor $RELEASE_VERSION`
 
 checkout "v$RELEASE_VERSION"
 checkoutOnANewBranch "$BRANCH_NAME"
-updatePomfileVersions "$NEXT_BRANCH_VERSION"-SNAPSHOT
-addAllModificationsAndCommitWithMessage "Updating poms for ""$NEXT_BRANCH_VERSION""-SNAPSHOT development"
+updatePomfileVersions "$BRANCH_VERSION"-SNAPSHOT
+addAllModificationsAndCommitWithMessage "Updating poms for ""$BRANCH_VERSION""-SNAPSHOT development"
 echo
