Added script for removing old release candidates

diff --git a/bin/rmgrelc b/bin/rmgrelc
--- a/bin/rmgrelc
+++ b/bin/rmgrelc
@@ -1,5 +1,5 @@
 #!/bin/bash
-#     ji-gitrel-mvn-1.0.3 - grelc
+#     ji-gitrel-mvn-1.0.4 - rmgrelc
 #
 #     Copyright (c) 2014,2015 Jirvan Pty Ltd
 #     All rights reserved.
@@ -32,29 +32,19 @@ source gitrellib.sh
 verifyNoUncommittedChanges
 verifyNoUnpushedCommits
 verifyHeadIsNotDetached
-verifyPomFileHasASnapshotVersion
 
-ORIG_BRANCH=`git branch| grep '^\* '|sed 's/\* //'`
+if [ "$1" = "" ]
+then
+    echo
+    echo "ERROR: release version associated with release candidates must be provided"
+    echo
+    exit 1
+fi
+RELEASE_VERSION="$1"
 
-# Extract release version etc
-echo
-echo "  - Extracting version from POM file snapshot version"
-RELEASE_VERSION=`mvn blah|egrep '^\[INFO\] Building .+ [0-9]+\.[0-9.]*[0-9]+-SNAPSHOT$'|sed 's/\[INFO\] Building .* //'|sed 's/-SNAPSHOT$//'`
-LAST_RELEASE_CANDIDATE_NUMBER=`git tag|egrep '^v'$RELEASE_VERSION'_rc[0-9]+$'|sed 's/v'$RELEASE_VERSION'_rc/'/|sort -n|tail -n 1`
-NEXT_RELEASE_CANDIDATE_NUMBER=$(($LAST_RELEASE_CANDIDATE_NUMBER + 1))
-RELEASE_CANDIDATE_VERSION="$RELEASE_VERSION""_rc"$NEXT_RELEASE_CANDIDATE_NUMBER
+confimBeforeProceeding "   Do you want to remove all release candidates associated with $RELEASE_VERSION (y/n) ?"
 
-verifyTagDoesNotExist "v$RELEASE_VERSION"
-confimBeforeProceeding "  Do you wish to create release candidate v$RELEASE_CANDIDATE_VERSION (y/n) ?"
-
-# Create a POM version modified and tagged version on a temp branch then return to original branch
-TEMP_BRANCH="v$RELEASE_CANDIDATE_VERSION""_tmpBranch"
-checkoutOnANewBranch $TEMP_BRANCH
-updateProjectAndModulePomfileVersions $RELEASE_CANDIDATE_VERSION
-addAllModificationsAndCommitWithMessage "v"$RELEASE_CANDIDATE_VERSION
-tagAndPushTagToOrigin v$RELEASE_CANDIDATE_VERSION
-checkout $ORIG_BRANCH
-tagAndPushTagToOrigin "v"$RELEASE_CANDIDATE_VERSION"_created"
-deleteBranch $TEMP_BRANCH
+# Archive redundant release candidate tags
+archiveIfNecessaryAndRemoveRedundantReleaseCandidateTags $RELEASE_VERSION
 
 echo
